name: print-name

on:
  push:
    branches: [ main ]

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello from print-name!" > message.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: greeting-message
          path: message.txt

